### ISSUE TITLE
崩溃了我吧这个。

### ISSUE THREAD

**Issue by sunnymooni** [tianzhijiexian/logger#3]
01-22 16:45:11.093 9962-9962/? E/MainActivity: ║ something happened
01-22 16:45:11.093 9962-9962/? E/MainActivity: ║ java.lang.ClassNotFoundException: kale
01-22 16:45:11.093 9962-9962/? E/MainActivity: ║ 	at java.lang.Class.classForName(Native Method)
01-22 16:45:11.093 9962-9962/? E/MainActivity: ║ 	at java.lang.Class.forName(Class.java:324)
01-22 16:45:11.093 9962-9962/? E/MainActivity: ║ 	at java.lang.Class.forName(Class.java:285)
01-22 16:45:11.093 9962-9962/? E/MainActivity: ║ 	at com.orhanobut.loggersample.MainActivity.levTest(MainActivity.java:72)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at com.orhanobut.loggersample.MainActivity.onCreate(MainActivity.java:42)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at android.app.Activity.performCreate(Activity.java:6298)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2608)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at android.os.Handler.dispatchMessage(Handler.java:111)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at android.os.Looper.loop(Looper.java:207)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at android.app.ActivityThread.main(ActivityThread.java:5896)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at java.lang.reflect.Method.invoke(Native Method)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ Caused by: java.lang.ClassNotFoundException: Didn't find class "kale" on path: DexPathList[[dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-support-annotations-25.0.0_a0be79355e8e92409d15e9ade10730bcacf4b295-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-internal_impl-25.0.0_a6e27fc9d86bdf4eeba72ee8b0e88c421310e965-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-internal_impl-25.0.0_79b887a6765bc52d00adc84dee5a350f934b6cd3-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-internal_impl-25.0.0_6b25bf735a0c360ccd743b67d58990fa01eece1c-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-internal_impl-25.0.0_4d5b5c4ef4df83f30423d2f421d0ac4d2ca5b6b5-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-internal_impl-25.0.0_177ba7020f0d91168ce2333825b0f0bc47441531-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.jakewharton.timber-timber-4.4.0_cc222fe38dc0f0f44b3f8351708c0cd3e931ac2b-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-vector-drawable-25.0.0_a1520134598de5dd60002d5fa53237e525c47140-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-v4-25.0.0_413a8070dfc969a274e31916aad896d60176e5da-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-media-compat-25.0.0_05da84e407c5a1213308a30f6fd34c7f975b17a1-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-fragment-25.0.0_28f51472be960ac025bd02e572708ccd26472c4b-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-core-utils-25.0.0_72f2bc24c094df160b809f78cf3000bdcca5cb46-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-core-ui-25.0.0_2279163fbc35f2b21bff2fe153a5ec96d0acd069-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-compat-25.0.0_7af99bbe8d820a3d63b2e254ccb9c7b85df4d43c-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-appcompat-v7-25.0.0_49beeecff53475880efab1dc4e938517c3084e12-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-25.0.0_aa0f8c4f1748594c6932f3c0c61a086a5bb27053-classes.dex"],nativeLibraryDirectories=[/data/app/com.orhanobut.loggersample-1/lib/arm64, /vendor/lib64, /system/lib64]]
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	... 17 more
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "kale" on path: DexPathList[[zip file "/data/app/com.orhanobut.loggersample-1/base.apk"],nativeLibraryDirectories=[/data/app/com.orhanobut.loggersample-1/lib/arm64, /vendor/lib64, /system/lib64]]
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
01-22 16:45:11.094 9962-9962/? E/MainActivity: ║ 		... 18 more
01-22 16:45:11.095 9962-9962/? E/MainActivity: ║ 		Suppressed: java.lang.ClassNotFoundException: Didn't find class "kale" on path: DexPathList[[dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-support-annotations-25.0.0_a0be79355e8e92409d15e9ade10730bcacf4b295-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-internal_impl-25.0.0_a6e27fc9d86bdf4eeba72ee8b0e88c421310e965-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-internal_impl-25.0.0_79b887a6765bc52d00adc84dee5a350f934b6cd3-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-internal_impl-25.0.0_6b25bf735a0c360ccd743b67d58990fa01eece1c-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-internal_impl-25.0.0_4d5b5c4ef4df83f30423d2f421d0ac4d2ca5b6b5-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-internal_impl-25.0.0_177ba7020f0d91168ce2333825b0f0bc47441531-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.jakewharton.timber-timber-4.4.0_cc222fe38dc0f0f44b3f8351708c0cd3e931ac2b-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-vector-drawable-25.0.0_a1520134598de5dd60002d5fa53237e525c47140-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-v4-25.0.0_413a8070dfc969a274e31916aad896d60176e5da-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-media-compat-25.0.0_05da84e407c5a1213308a30f6fd34c7f975b17a1-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-fragment-25.0.0_28f51472be960ac025bd02e572708ccd26472c4b-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-core-utils-25.0.0_72f2bc24c094df160b809f78cf3000bdcca5cb46-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-core-ui-25.0.0_2279163fbc35f2b21bff2fe153a5ec96d0acd069-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-support-compat-25.0.0_7af99bbe8d820a3d63b2e254ccb9c7b85df4d43c-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-appcompat-v7-25.0.0_49beeecff53475880efab1dc4e938517c3084e12-classes.dex", dex file "/data/data/com.orhanobut.loggersample/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-25.0.0_aa0f8c4f1748594c6932f3c0c61a086a5bb27053-classes.dex"],nativeLibraryDirectories=[/data/app/com.orhanobut.loggersample-1/lib/arm64, /vendor/lib64, /system/lib64]]
01-22 16:45:11.095 9962-9962/? E/MainActivity: ║ 			at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-22 16:45:11.095 9962-9962/? E/MainActivity: ║ 			at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
01-22 16:45:11.095 9962-9962/? E/MainActivity: ║ 			at com.android.tools.fd.runtime.IncrementalClassLoader.findClass(IncrementalClassLoader.java:62)
01-22 16:45:11.095 9962-9962/? E/MainActivity: ║ 			at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
01-22 16:45:11.095 9962-9962/? E/MainActivity: ║ 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
01-22 16:45:11.095 9962-9962/? E/MainActivity: ║ 			... 19 more
01-22 16:45:11.095 9962-9962/? E/MainActivity: ║ 			Suppressed: java.lang.ClassNotFoundException: kale
01-22 16:45:11.095 9962-9962/? E/MainActivity: ║ 				at java.lang.Class.classForName(Native Method)
01-22 16:45:11.095 9962-9962/? E/MainActivity: ║ 				at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
01-22 16:45:11.095 9962-9962/? E/MainActivity: ║ 				at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
01-22 16:45:11.095 9962-9962/? E/MainActivity: ║ 				at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
01-22 16:45:11.095 9962-9962/? E/MainActivity: ║ 				... 20 more
01-22 16:45:11.095 9962-9962/? E/MainActivity: ╚ 			Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available ==> levTest(MainActivity.java:74) Thread: main
01-22 16:45:11.239 9962-9962/? E/OpenGLRenderer: PerfServiceNative_notifyRenderTime init fail!
01-22 16:45:11.282 9962-9981/? E/GED: Failed to get GED Log Buf, err(0)

**Comment by kaleai** [comment]
嗯嗯 是的
